# Generated by Django 4.2.1 on 2023-06-09 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='auteur',
            new_name='prix',
        ),
        migrations.AddField(
            model_name='produits',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driveapp.categories'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='num_client',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produits',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits_images'),
        ),
    ]
