# Generated by Django 4.2.2 on 2023-06-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driveapp', '0002_rename_auteur_produits_prix_produits_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produits',
            name='photo',
        ),
        migrations.AddField(
            model_name='commandes',
            name='clients',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driveapp.clients'),
        ),
        migrations.AddField(
            model_name='commandes',
            name='produit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='driveapp.produits'),
        ),
        migrations.AddField(
            model_name='produits',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='produits_images/'),
        ),
        migrations.AddField(
            model_name='produits',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produits',
            name='categories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='driveapp.categories'),
        ),
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driveapp.commandes')),
            ],
        ),
    ]
